version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: laravel-sample
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: {}
